"""updated booking table

Revision ID: 01844c0bd737
Revises: 2c6de539b677
Create Date: 2025-10-11 10:28:04.802514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01844c0bd737'
down_revision: Union[str, Sequence[str], None] = '2c6de539b677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('booking', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('booking', sa.Column('expires_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('booking', sa.Column('stripe_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('booking', sa.Column('stripe_payment_intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'stripe_payment_intent')
    op.drop_column('booking', 'stripe_session_id')
    op.drop_column('booking', 'expires_at')
    op.drop_column('booking', 'amount')
    op.drop_column('booking', 'status')
    # ### end Alembic commands ###
