"""Added review table and updated user and house tables

Revision ID: 1f9015d4e0e3
Revises: 54c423e39601
Create Date: 2025-10-06 20:31:42.746554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1f9015d4e0e3'
down_revision: Union[str, Sequence[str], None] = '54c423e39601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('review_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('house_uid', sa.Uuid(), nullable=True),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['house_uid'], ['houses.house_uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['Users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.add_column('booking', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('booking', sa.Column('end_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'end_date')
    op.drop_column('booking', 'start_date')
    op.drop_table('reviews')
    # ### end Alembic commands ###
