"""Added review table and updated user and house tables

Revision ID: 2e774082ebc7
Revises: 9c55c8aa0ef7
Create Date: 2025-10-06 22:22:32.228197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e774082ebc7'
down_revision: Union[str, Sequence[str], None] = '9c55c8aa0ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
