"""updated house table

Revision ID: 625f916b4cdd
Revises: 2e774082ebc7
Create Date: 2025-10-06 22:38:20.878985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625f916b4cdd'
down_revision: Union[str, Sequence[str], None] = '2e774082ebc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('Available', sa.BOOLEAN,nullable=False))
    op.drop_column('houses', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('houses', 'Available')
    # ### end Alembic commands ###
