"""Init database

Revision ID: d932369ca66c
Revises: 
Create Date: 2025-10-16 19:59:06.486150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd932369ca66c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('house_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('houses', sa.Column('available', sa.Boolean(), nullable=False))
    op.drop_column('houses', 'Available')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('Available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('houses', 'available')
    op.drop_column('houses', 'house_image_url')
    # ### end Alembic commands ###
