"""updated house table

Revision ID: f43bf652668c
Revises: ed7ec996c59f
Create Date: 2025-10-07 21:05:31.540260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43bf652668c'
down_revision: Union[str, Sequence[str], None] = 'ed7ec996c59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('rating', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'rating')
    # ### end Alembic commands ###
