"""updating House model

Revision ID: fc5135156212
Revises: 01844c0bd737
Create Date: 2025-10-16 13:56:11.080208

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5135156212'
down_revision: Union[str, Sequence[str], None] = '01844c0bd737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('houses', sa.Column('bedroom', sa.Integer(), nullable=False))
    op.add_column('houses', sa.Column('bathroom', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'bathroom')
    op.drop_column('houses', 'bedroom')
    op.drop_column('houses', 'state')
    # ### end Alembic commands ###
